[project]
name = "am-i-a-terminal-artisan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cython>=3.1.5",
    "lookatme>=3.0.0rc5",
    "setuptools>=80.9.0",
]
